// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe4Bz1uf8k1WGLhiFM5W7Mi9QAwDAZWl4',
    appId: '1:121300235055:web:1fa803dacfb966fbf7e7da',
    messagingSenderId: '121300235055',
    projectId: 'fasum-app-c9db5',
    authDomain: 'fasum-app-c9db5.firebaseapp.com',
    storageBucket: 'fasum-app-c9db5.firebasestorage.app',
    measurementId: 'G-W2SXN1JQR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxWiGJEwTzLOsFXLfEHPAojyEPDwSrp1g',
    appId: '1:121300235055:android:e8a0f9d043a2c975f7e7da',
    messagingSenderId: '121300235055',
    projectId: 'fasum-app-c9db5',
    storageBucket: 'fasum-app-c9db5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBrCNIxVcwDH9CeQ4TABGETiz9B3a7NBg',
    appId: '1:121300235055:ios:7c4091e818519884f7e7da',
    messagingSenderId: '121300235055',
    projectId: 'fasum-app-c9db5',
    storageBucket: 'fasum-app-c9db5.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );
}
